package com.meng.gameData.TouHou.zun;

import com.meng.gameData.TouHou.*;

public class TH06GameData {
	public static final String gameName="东方红魔乡 ~ the Embodiment of Scarlet Devil.";
	public static final String gameNameCN="东方红魔乡";
	public static final String gameNameAbbr="EoSD";
	public static String[] players = new String[]{"博丽灵梦 灵符", "博丽灵梦 梦符", "雾雨魔理沙 魔符", "雾雨魔理沙 恋符"};
	public static String[] charaName=new String[]{
		"露米娅",
		"大妖精",
		"琪露诺",
		"红美铃",
		"帕秋莉·诺蕾姬",
		"十六夜咲夜",
		"蕾米莉亚·斯卡雷特",
		"芙兰朵露·斯卡雷特",
	};
	public static String[] musicName=new String[]{
		"比赤色更红的梦",
		"如鬼灯般的红色之魂",
		"妖魔夜行",
		"Lunate Elf",
		"活泼的纯情小姑娘",
		"上海红茶馆 ~ Chinese Tea",
		"明治十七年的上海爱丽丝",
		"巴瓦鲁魔法图书馆",
		"Locked Girl ~ 少女密室",
		"女仆与血之怀表",
		"月时计 ~ Luna Dial",
		"特佩斯的年幼末裔",
		"献给已逝公主的七重奏",
		"魔法少女们的百年祭",
		"U.N.OWEN就是她吗？",
		"比红色更虚无的永远",
		"红楼 ~ Eastern Dream...",
	};
	public static SpellCard[] spellcards=new SpellCard[]{
		new SpellCard("月符「月光」", "露米娅", SpellCard.Hard),
		new SpellCard("月符「月光」", "露米娅", SpellCard.Lunatic),
		new SpellCard("夜符「夜雀」", "露米娅", SpellCard.Easy),
		new SpellCard("夜符「夜雀」", "露米娅", SpellCard.Normal),
		new SpellCard("夜符「夜雀」", "露米娅", SpellCard.Hard),
		new SpellCard("夜符「夜雀」", "露米娅", SpellCard.Lunatic),
		new SpellCard("暗符「境界线」", "露米娅", SpellCard.Easy),
		new SpellCard("暗符「境界线」", "露米娅", SpellCard.Normal),
		new SpellCard("暗符「境界线」", "露米娅", SpellCard.Hard),
		new SpellCard("暗符「境界线」", "露米娅", SpellCard.Lunatic),
		new SpellCard("冰符「冰瀑」", "琪露诺", SpellCard.Easy),
		new SpellCard("冰符「冰瀑」", "琪露诺", SpellCard.Normal),
		new SpellCard("雹符「冰雹暴风」", "琪露诺", SpellCard.Hard),
		new SpellCard("雹符「冰雹暴风」", "琪露诺", SpellCard.Lunatic),
		new SpellCard("冻符「完美冻结」", "琪露诺", SpellCard.Easy),
		new SpellCard("冻符「完美冻结」", "琪露诺", SpellCard.Normal),
		new SpellCard("冻符「完美冻结」", "琪露诺", SpellCard.Hard),
		new SpellCard("冻符「完美冻结」", "琪露诺", SpellCard.Lunatic),
		new SpellCard("雪符「钻石风暴」", "琪露诺", SpellCard.Normal),
		new SpellCard("雪符「钻石风暴」", "琪露诺", SpellCard.Hard),
		new SpellCard("雪符「钻石风暴」", "琪露诺", SpellCard.Lunatic),
		new SpellCard("华符「芳华绚烂」", "红美铃", SpellCard.Easy),
		new SpellCard("华符「芳华绚烂」", "红美铃", SpellCard.Normal),
		new SpellCard("华符「Selaginella 9」", "红美铃", SpellCard.Hard),
		new SpellCard("华符「Selaginella 9」", "红美铃", SpellCard.Lunatic),
		new SpellCard("虹符「彩虹风铃」", "红美铃", SpellCard.Easy),
		new SpellCard("虹符「彩虹风铃」", "红美铃", SpellCard.Normal),
		new SpellCard("虹符「彩虹风铃」", "红美铃", SpellCard.Hard),
		new SpellCard("虹符「彩虹风铃」", "红美铃", SpellCard.Lunatic),
		new SpellCard("幻符「华想梦葛」", "红美铃", SpellCard.Hard),
		new SpellCard("幻符「华想梦葛」", "红美铃", SpellCard.Lunatic),
		new SpellCard("彩符「彩雨」", "红美铃", SpellCard.Easy),
		new SpellCard("彩符「彩雨」", "红美铃", SpellCard.Normal),
		new SpellCard("彩符「彩光乱舞」", "红美铃", SpellCard.Hard),
		new SpellCard("彩符「彩光乱舞」", "红美铃", SpellCard.Lunatic),
		new SpellCard("彩符「极彩台风」", "红美铃", SpellCard.Normal),
		new SpellCard("彩符「极彩台风」", "红美铃", SpellCard.Hard),
		new SpellCard("彩符「极彩台风」", "红美铃", SpellCard.Lunatic),
		new SpellCard("火符「火神之光」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("火符「火神之光」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("水符「水精公主」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("水符「水精公主」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("木符「风灵的角笛」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("木符「风灵的角笛」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("土符「慵懒三石塔」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("土符「慵懒三石塔」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("金符「金属疲劳」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("火符「火神之光 上级」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("火符「火神之光 上级」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("火符「火神之光 上级」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("木符「风灵的角笛 上级」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("木符「风灵的角笛 上级」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("木符「风灵的角笛 上级」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("土符「慵懒三石塔 上级」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("土符「慵懒三石塔 上级」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("土符「慵懒三石塔 上级」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("水符「湖葬」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("水符「湖葬」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("木符「翠绿风暴」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("木符「翠绿风暴」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("土符「三石塔的震动」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("土符「三石塔的震动」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("金符「银龙」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("金符「银龙」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("火&土符「环状熔岩带」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("火&土符「环状熔岩带」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("火&土符「环状熔岩带」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("火&土符「环状熔岩带」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("木&火符「森林大火」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("木&火符「森林大火」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("木&火符「森林大火」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("木&火符「森林大火」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("水&木符「水精灵」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("水&木符「水精灵」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("水&木符「水精灵」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("水&木符「水精灵」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("金&水符「水银之毒」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("金&水符「水银之毒」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("金&水符「水银之毒」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("土&金符「翡翠巨石」", "帕秋莉·诺蕾姬", SpellCard.Easy),
		new SpellCard("土&金符「翡翠巨石」", "帕秋莉·诺蕾姬", SpellCard.Normal),
		new SpellCard("土&金符「翡翠巨石」", "帕秋莉·诺蕾姬", SpellCard.Hard),
		new SpellCard("土&金符「翡翠巨石」", "帕秋莉·诺蕾姬", SpellCard.Lunatic),
		new SpellCard("奇术「误导」", "十六夜咲夜", SpellCard.Easy),
		new SpellCard("奇术「误导」", "十六夜咲夜", SpellCard.Normal),
		new SpellCard("奇术「幻惑误导」", "十六夜咲夜", SpellCard.Hard),
		new SpellCard("奇术「幻惑误导」", "十六夜咲夜", SpellCard.Lunatic),
		new SpellCard("幻在「钟表的残骸」", "十六夜咲夜", SpellCard.Easy),
		new SpellCard("幻在「钟表的残骸」", "十六夜咲夜", SpellCard.Normal),
		new SpellCard("幻幽「迷幻杰克」", "十六夜咲夜", SpellCard.Hard),
		new SpellCard("幻幽「迷幻杰克」", "十六夜咲夜", SpellCard.Lunatic),
		new SpellCard("幻象「月神之钟」", "十六夜咲夜", SpellCard.Easy),
		new SpellCard("幻象「月神之钟」", "十六夜咲夜", SpellCard.Normal),
		new SpellCard("幻世「世界」", "十六夜咲夜", SpellCard.Hard),
		new SpellCard("幻世「世界」", "十六夜咲夜", SpellCard.Lunatic),
		new SpellCard("女仆秘技「操弄玩偶」", "十六夜咲夜", SpellCard.Easy),
		new SpellCard("女仆秘技「操弄玩偶」", "十六夜咲夜", SpellCard.Normal),
		new SpellCard("女仆秘技「杀人玩偶」", "十六夜咲夜", SpellCard.Hard),
		new SpellCard("女仆秘技「杀人玩偶」", "十六夜咲夜", SpellCard.Lunatic),
		new SpellCard("奇术「永恒的温柔」", "十六夜咲夜", SpellCard.Easy),
		new SpellCard("奇术「永恒的温柔」", "十六夜咲夜", SpellCard.Normal),
		new SpellCard("奇术「永恒的温柔」", "十六夜咲夜", SpellCard.Hard),
		new SpellCard("奇术「永恒的温柔」", "十六夜咲夜", SpellCard.Lunatic),
		new SpellCard("天罚「大卫之星」", "蕾米莉亚·斯卡雷特", SpellCard.Easy),
		new SpellCard("天罚「大卫之星」", "蕾米莉亚·斯卡雷特", SpellCard.Normal),
		new SpellCard("神罚「年幼的恶魔之王」", "蕾米莉亚·斯卡雷特", SpellCard.Hard),
		new SpellCard("神罚「年幼的恶魔之王」", "蕾米莉亚·斯卡雷特", SpellCard.Lunatic),
		new SpellCard("冥符「红色的冥界」", "蕾米莉亚·斯卡雷特", SpellCard.Easy),
		new SpellCard("冥符「红色的冥界」", "蕾米莉亚·斯卡雷特", SpellCard.Normal),
		new SpellCard("狱符「千根针的针山」", "蕾米莉亚·斯卡雷特", SpellCard.Hard),
		new SpellCard("狱符「千根针的针山」", "蕾米莉亚·斯卡雷特", SpellCard.Lunatic),
		new SpellCard("诅咒「弗拉德·特佩斯的诅咒」", "蕾米莉亚·斯卡雷特", SpellCard.Easy),
		new SpellCard("诅咒「弗拉德·特佩斯的诅咒」", "蕾米莉亚·斯卡雷特", SpellCard.Normal),
		new SpellCard("神术「吸血鬼幻想」", "蕾米莉亚·斯卡雷特", SpellCard.Hard),
		new SpellCard("神术「吸血鬼幻想」", "蕾米莉亚·斯卡雷特", SpellCard.Lunatic),
		new SpellCard("红符「绯红射击」", "蕾米莉亚·斯卡雷特", SpellCard.Easy),
		new SpellCard("红符「绯红射击」", "蕾米莉亚·斯卡雷特", SpellCard.Normal),
		new SpellCard("红符「绯红之主」", "蕾米莉亚·斯卡雷特", SpellCard.Hard),
		new SpellCard("红符「绯红之主」", "蕾米莉亚·斯卡雷特", SpellCard.Lunatic),
		new SpellCard("「Red Magic」", "蕾米莉亚·斯卡雷特", SpellCard.Normal),
		new SpellCard("「红色的幻想乡」", "蕾米莉亚·斯卡雷特", SpellCard.Hard),
		new SpellCard("「红色的幻想乡」", "蕾米莉亚·斯卡雷特", SpellCard.Lunatic),
		new SpellCard("月符「静息的月神」", "帕秋莉·诺蕾姬", SpellCard.Extra),
		new SpellCard("日符「皇家烈焰」", "帕秋莉·诺蕾姬", SpellCard.Extra),
		new SpellCard("火水木金土符「贤者之石」", "帕秋莉·诺蕾姬", SpellCard.Extra),
		new SpellCard("禁忌「红莓陷阱」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁忌「莱瓦汀」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁忌「四重存在」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁忌「笼中鸟」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁忌「恋之迷宫」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁弹「星弧破碎」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁弹「折反射」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("禁弹「刻着过去的钟表」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("秘弹「之后就一个人都没有了吗？」", "芙兰朵露·斯卡雷特", SpellCard.Extra),
		new SpellCard("QED「495年的波纹」", "芙兰朵露·斯卡雷特", SpellCard.Extra)
	};
	public static String[] spells=new String[]{
		"月符「月光」",
		"夜符「夜雀」",
		"暗符「境界线」",

		"冰符「冰瀑」",
		"雹符「冰雹暴风」",
		"冻符「完美冻结」",
		"雪符「钻石风暴」",

		"华符「芳华绚烂」",
		"华符「Selaginella 9」",
		"虹符「彩虹风铃」",
		"幻符「华想梦葛」",
		"彩符「彩雨」",
		"彩符「彩光乱舞」",
		"彩符「极彩台风」",

		"火符「火神之光」",
		"水符「水精公主」",
		"木符「风灵的角笛」",
		"土符「慵懒三石塔」",
		"金符「金属疲劳」",
		"火符「火神之光 上级」",
		"木符「风灵的角笛 上级」",
		"土符「慵懒三石塔 上级」",
		"火符「火神之光」",
		"水符「湖葬」",
		"木符「翠绿风暴」",
		"土符「三石塔的震动」",
		"金符「银龙」",
		"火&土符「环状熔岩带」",
		"木&火符「森林大火」",
		"水&木符「水精灵」",
		"金&水符「水银之毒」",
		"土&金符「翡翠巨石」",

		"奇术「误导」",
		"奇术「幻惑误导」",
		"幻在「钟表的残骸」",
		"幻幽「迷幻杰克」",
		"幻象「月神之钟」",
		"幻世「世界」",
		"女仆秘技「操弄玩偶」",
		"女仆秘技「杀人玩偶」",

		"奇术「永恒的温柔」",

		"天罚「大卫之星」",
		"神罚「年幼的恶魔之王」",
		"冥符「红色的冥界」",
		"狱符「千根针的针山」",
		"诅咒「弗拉德·特佩斯的诅咒」",
		"神术「吸血鬼幻想」",
		"红符「绯红射击」",
		"红符「绯红之主」",
		"「Red Magic」",
		"「红色的幻想乡」",		

		"月符「静息的月神」",
		"日符「皇家烈焰」",
		"火水木金土符「贤者之石」",

		"禁忌「红莓陷阱」",
		"禁忌「莱瓦汀」",
		"禁忌「四重存在」",
		"禁忌「笼中鸟」",
		"禁忌「恋之迷宫」",
		"禁弹「星弧破碎」",
		"禁弹「折反射」",
		"禁弹「刻着过去的钟表」",
		"秘弹「之后就一个人都没有了吗？」",
		"QED「495年的波纹」"
	};
}
