package com.meng.gameData.TouHou.zun;
import com.meng.gameData.TouHou.*;

public class TH08GameData {
	public static final String gameName="东方永夜抄 ~ Imperishable Night.";
	public static final String gameNameCN="东方永夜抄";
	public static final String gameNameAbbr="IN";
	public static String[] players = new String[]{"幻想的结界组", "咏唱禁咒组", "梦幻的红魔组", "幽冥之住人组", "博丽灵梦", "八云紫", "雾雨魔理沙", "爱丽丝·玛格特罗依德", "蕾米莉亚·斯卡蕾特", "十六夜咲夜", "西行寺幽幽子", "魂魄妖梦"};
	public static String[] charaName=new String[]{
		"莉格露",
		"米斯蒂娅·萝蕾拉",
		"上白泽慧音",
		"博丽灵梦",
		"雾雨魔理沙",
		"因幡帝",
		"铃仙·优昙华院·因幡",
		"八意永琳",
		"蓬莱山辉夜",
		"藤原妹红"
	};
	public static String[] musicName=new String[]{
		"永夜抄 ~ Eastern Night.",
		"幻视之夜 ~ Ghostly Eyes",
		"蠢蠢的秋月 ~ Mooned Insect",
		"夜雀的歌声 ~ Night Bird",
		"已经只能听见歌声了",
		"令人怀念的东方之血 ~ Old World",
		"Plain Asia",
		"永夜的报应 ~ Imperishable Night",
		"少女绮想曲 ~ Dream Battle",
		"恋色Master spark",
		"灰姑娘的笼子 ~ Kagome-Kagome",
		"狂气之瞳 ~ Invisible Full Moon",
		"旅人1969",
		"千年幻想乡 ~ History of the Moon",
		"竹取飞翔 ~ Lunatic Princess",
		"旅人1970",
		"Extend Ash ~ 蓬莱人",
		"飘上月球，不死之烟",
		"月见草",
		"Eternal Dream ~ 幽玄的枫树",
		"东方妖怪小町"	
	};
	public static SpellCard[] spellcards=new SpellCard[]{
		new SpellCard("萤符「地上的流星」", "莉格露·奈特巴格", 4),
		new SpellCard("萤符「地上的彗星」", "莉格露·奈特巴格", 8),
		new SpellCard("灯符「萤光现象」", "莉格露·奈特巴格", 15),
		new SpellCard("蠢符「小虫」", "莉格露·奈特巴格", 1),
		new SpellCard("蠢符「小虫风暴」", "莉格露·奈特巴格", 2),
		new SpellCard("蠢符「夜虫风暴」", "莉格露·奈特巴格", 4),
		new SpellCard("蠢符「夜虫龙卷」", "莉格露·奈特巴格", 8),
		new SpellCard("隐虫「永夜蛰居」", "莉格露·奈特巴格", 64),
		new SpellCard("声符「枭的夜鸣声」", "米斯蒂娅·萝蕾拉", 3),
		new SpellCard("声符「木菟的咆哮」", "米斯蒂娅·萝蕾拉", 12),
		new SpellCard("蛾符「天蛾的蛊道」", "米斯蒂娅·萝蕾拉", 3),
		new SpellCard("毒符「毒蛾的鳞粉」", "米斯蒂娅·萝蕾拉", 4),
		new SpellCard("猛毒「毒蛾的黑暗演舞」", "米斯蒂娅·萝蕾拉", 8),
		new SpellCard("鹰符「祸延疾冲」", "米斯蒂娅·萝蕾拉", 15),
		new SpellCard("夜盲「夜雀之歌」", "米斯蒂娅·萝蕾拉", 15),
		new SpellCard("夜雀「午夜的合唱指挥」", "米斯蒂娅·萝蕾拉", 64),
		new SpellCard("产灵「最初的金字塔」", "上白泽慧音", 15),
		new SpellCard("始符「短暂的137」", "上白泽慧音", 14),
		new SpellCard("野符「武烈的危机」", "上白泽慧音", 1),
		new SpellCard("野符「将门的危机」", "上白泽慧音", 2),
		new SpellCard("野符「义满的危机」", "上白泽慧音", 4),
		new SpellCard("野符「GHQ的危机」", "上白泽慧音", 8),
		new SpellCard("国符「三种神器 剑」", "上白泽慧音", 1),
		new SpellCard("国符「三种神器 玉」", "上白泽慧音", 2),
		new SpellCard("国符「三种神器 镜」", "上白泽慧音", 4),
		new SpellCard("国体「三种神器 乡」", "上白泽慧音", 8),
		new SpellCard("终符「幻想天皇」", "上白泽慧音", 3),
		new SpellCard("虚史「幻想乡传说」", "上白泽慧音", 12),
		new SpellCard("未来「高天原」", "上白泽慧音", 64),
		new SpellCard("梦符「二重结界」", "博丽灵梦", 3),
		new SpellCard("梦境「二重大结界」", "博丽灵梦", 12),
		new SpellCard("灵符「梦想封印 散」", "博丽灵梦", 3),
		new SpellCard("散灵「梦想封印 寂」", "博丽灵梦", 12),
		new SpellCard("梦符「封魔阵」", "博丽灵梦", 3),
		new SpellCard("神技「八方鬼缚阵」", "博丽灵梦", 4),
		new SpellCard("神技「八方龙杀阵」", "博丽灵梦", 8),
		new SpellCard("灵符「梦想封印 集」", "博丽灵梦", 3),
		new SpellCard("回灵「梦想封印 侘」", "博丽灵梦", 12),
		new SpellCard("境界「二重弹幕结界」", "博丽灵梦", 3),
		new SpellCard("大结界「博丽弹幕结界」", "博丽灵梦", 12),
		new SpellCard("神灵「梦想封印 瞬」", "博丽灵梦", 64),
		new SpellCard("魔符「银河」", "雾雨魔理沙", 3),
		new SpellCard("魔空「小行星带」", "雾雨魔理沙", 12),
		new SpellCard("魔符「星尘幻想」", "雾雨魔理沙", 3),
		new SpellCard("黑魔「黑洞边缘」", "雾雨魔理沙", 12),
		new SpellCard("恋符「非定向光线」", "雾雨魔理沙", 3),
		new SpellCard("恋风「星光台风」", "雾雨魔理沙", 12),
		new SpellCard("恋符「极限火花」", "雾雨魔理沙", 3),
		new SpellCard("恋心「二重火花」", "雾雨魔理沙", 12),
		new SpellCard("光符「地球光」", "雾雨魔理沙", 3),
		new SpellCard("光击「击月」", "雾雨魔理沙", 12),
		new SpellCard("魔炮「Final Spark」", "雾雨魔理沙", 64),
		new SpellCard("魔炮「Final Master Spark」", "雾雨魔理沙", 64),
		new SpellCard("波符「赤眼催眠(Mind Shaker)」", "铃仙·优昙华院·因幡", 3),
		new SpellCard("幻波「赤眼催眠(Mind Blowing)」", "铃仙·优昙华院·因幡", 12),
		new SpellCard("狂符「幻视调律(Visionary Tuning)」", "铃仙·优昙华院·因幡", 3),
		new SpellCard("狂视「狂视调律(Illusion Seeker)」", "铃仙·优昙华院·因幡", 12),
		new SpellCard("懒符「生神停止(Idling Wave)」", "铃仙·优昙华院·因幡", 3),
		new SpellCard("懒惰「生神停止(Mind Stopper)」", "铃仙·优昙华院·因幡", 12),
		new SpellCard("散符「真实之月(Invisible Full Moon)」", "铃仙·优昙华院·因幡", 15),
		new SpellCard("月眼「月兔远隔催眠术(Tele-Mesmerism)」", "铃仙·优昙华院·因幡", 64),
		new SpellCard("天丸「壶中的天地」", "八意永琳", 15),
		new SpellCard("觉神「神代的记忆」", "八意永琳", 3),
		new SpellCard("神符「天人的族谱」", "八意永琳", 12),
		new SpellCard("苏活「生命游戏 -Life Game-」", "八意永琳", 3),
		new SpellCard("苏生「Rising Game」", "八意永琳", 12),
		new SpellCard("操神「思兼装置」", "八意永琳", 3),
		new SpellCard("神脑「思兼的头脑」", "八意永琳", 12),
		new SpellCard("天咒「阿波罗13」", "八意永琳", 15),
		new SpellCard("秘术「天文密葬法」", "八意永琳", 15),
		new SpellCard("禁药「蓬莱之药」", "八意永琳", 64),
		new SpellCard("药符「壶中的大银河」", "八意永琳", 15),
		new SpellCard("难题「龙颈之玉 -五色的弹丸-」", "蓬莱山辉夜", 3),
		new SpellCard("神宝「耀眼的龙玉」", "蓬莱山辉夜", 12),
		new SpellCard("难题「佛御石之钵 -不碎的意志-」", "蓬莱山辉夜", 3),
		new SpellCard("神宝「佛体的金刚石」", "蓬莱山辉夜", 12),
		new SpellCard("难题「火鼠的皮衣 -不焦躁的内心-」", "蓬莱山辉夜", 3),
		new SpellCard("神宝「火蜥蜴之盾」", "蓬莱山辉夜", 12),
		new SpellCard("难题「燕的子安贝 -永命线-」", "蓬莱山辉夜", 3),
		new SpellCard("神宝「无限的生命之泉」", "蓬莱山辉夜", 12),
		new SpellCard("难题「蓬莱的弹枝 -七色的弹幕-」", "蓬莱山辉夜", 3),
		new SpellCard("神宝「蓬莱的玉枝 -梦色之乡-」", "蓬莱山辉夜", 12),
		new SpellCard("「永夜返 -初月-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -新月-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -上弦月-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -待宵-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -子之刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -子时二刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -子时三刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -子时四刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -丑之刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -丑时二刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -丑时三刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -丑时四刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -寅之刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -寅时二刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -寅时三刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -寅时四刻-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -朝霭-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -拂晓-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -耀世的启明星-」", "蓬莱山辉夜", 64),
		new SpellCard("「永夜返 -光明之世-」", "蓬莱山辉夜", 64),
		new SpellCard("旧史「旧秘境史 -古代史-」", "上白泽慧音", 16),
		new SpellCard("转世「一条归桥」", "上白泽慧音", 16),
		new SpellCard("新史「新幻想史 -现代史-」", "上白泽慧音", 16),
		new SpellCard("时效「月岩笠的诅咒」", "藤原妹红", 16),
		new SpellCard("不死「火鸟 -凤翼天翔-」", "藤原妹红", 16),
		new SpellCard("藤原「灭罪寺院伤」", "藤原妹红", 16),
		new SpellCard("不死「徐福时空」", "藤原妹红", 16),
		new SpellCard("灭罪「正直者之死」", "藤原妹红", 16),
		new SpellCard("虚人「无一」", "藤原妹红", 16),
		new SpellCard("不灭「不死鸟之尾」", "藤原妹红", 16),
		new SpellCard("蓬莱「凯风快晴 -Fujiyama Volcano-」", "藤原妹红", 16),
		new SpellCard("「不死鸟附体」", "藤原妹红", 16),
		new SpellCard("「蓬莱人形」", "藤原妹红", 16),
		new SpellCard("「不朽的弹幕」", "藤原妹红", 64),
		new SpellCard("「不合时令的蝶雨」", "莉格露·奈特巴格", 128),
		new SpellCard("「失明的夜雀」", "米斯蒂娅·萝蕾拉", 128),
		new SpellCard("「日出之国的天子」", "上白泽慧音", 128),
		new SpellCard("「似有似无的净化」", "上白泽慧音", 128),
		new SpellCard("「Ancient Duper」", "因幡帝", 128),
		new SpellCard("「幻胧月睨（Lunatic Red Eyes）」", "铃仙·优昙华院·因幡", 128),
		new SpellCard("「天网蛛网捕蝶之法」", "八意永琳", 128),
		new SpellCard("「蓬莱的树海」", "蓬莱山辉夜", 128),
		new SpellCard("「不死鸟重生」", "藤原妹红", 128),
		new SpellCard("「梦想天生」", "博丽灵梦", 128),
		new SpellCard("「Blazing Star」", "雾雨魔理沙", 128),
		new SpellCard("「收缩的世界」", "十六夜咲夜", 128),
		new SpellCard("「待宵反射卫星斩」", "魂魄妖梦", 128),
		new SpellCard("「猎奇剧团的怪人」", "爱丽丝·玛格特罗依德", 128),
		new SpellCard("「绯红的宿命」", "蕾米莉亚·斯卡雷特", 128),
		new SpellCard("「西行寺无余涅槃」", "西行寺幽幽子", 128),
		new SpellCard("「深弹幕结界 梦幻泡影」", "八云紫", 128)
	};
}
