package com.meng.gameData.TouHou.zun;

import com.meng.gameData.TouHou.*;

public class TH11GameData {
	public static final String gameName="东方地灵殿 ~ Subterranean Animism.";
	public static final String gameNameCN="东方地灵殿";
	public static final String gameNameAbbr="SA";
	public static String[] players = new String[]{"博丽灵梦 八云紫", "博丽灵梦 伊吹萃香", "博丽灵梦 射命丸文", "雾雨魔理沙 爱丽丝·玛格特罗依德", "雾雨魔理沙 帕秋莉", "雾雨魔理沙 河城荷取"};
	public static String[] charaName=new String[]{
		"琪斯美",
		"黑谷山女",
		"水桥帕露西",
		"星熊勇仪",
		"古明地觉",
		"火焰猫燐",
		"灵乌路空",
		"古明地恋"
	};
	public static String[] musicName=new String[]{
		"地灵们的起床",
		"昏暗的风穴",
		"被封印的妖怪 ~ Lost Place",
		"阻绝人迹之桥",
		"绿眼的嫉妒",
		"漫游旧地狱街道",
		"大江山的花之酒宴",
		"Heartfelt Fancy",
		"少女觉 ~ 3rd eye",
		"废狱摇篮曲",
		"尸体旅行 ~ Be of good cheer!",
		"业火地幔",
		"灵知的太阳信仰 ~ Nuclear Fusion",
		"Last Remote",
		"哈德曼的妖怪少女",
		"地灵们的归家",
		"能源黎明 ~ Future Dream...",
		"Player's Score"	
	};
	public static SpellCard[] spellcards=new SpellCard[]{
		new SpellCard("怪奇「钓瓶落之怪」", "琪斯美", 12),
		new SpellCard("罠符「捕捉之网」", "黑谷山女", 3),
		new SpellCard("蜘蛛「石窟的蜘蛛巢」", "黑谷山女", 12),
		new SpellCard("瘴符「瘴气场」", "黑谷山女", 3),
		new SpellCard("瘴气「原因不明的热病」", "黑谷山女", 12),
		new SpellCard("妒符「绿眼怪兽」", "水桥帕露西", 3),
		new SpellCard("嫉妒「看不见的绿眼怪兽」", "水桥帕露西", 12),
		new SpellCard("开花爷爷「对华丽的仁者之嫉妒」", "水桥帕露西", 3),
		new SpellCard("开花爷爷「小白的灰烬」", "水桥帕露西", 12),
		new SpellCard("剪舌麻雀「对谦虚的富者之记恨」", "水桥帕露西", 3),
		new SpellCard("剪舌麻雀「大葛笼与小葛笼」", "水桥帕露西", 12),
		new SpellCard("恨符「丑时参拜」", "水桥帕露西", 3),
		new SpellCard("恨符「丑时参拜第七日」", "水桥帕露西", 12),
		new SpellCard("鬼符「怪力乱神」", "星熊勇仪", 15),
		new SpellCard("怪轮「地狱之苦轮」", "星熊勇仪", 3),
		new SpellCard("枷符「罪人不释之枷」", "星熊勇仪", 12),
		new SpellCard("力业「大江山岚」", "星熊勇仪", 3),
		new SpellCard("力业「大江山颪」", "星熊勇仪", 12),
		new SpellCard("四天王奥义「三步必杀」", "星熊勇仪", 15),
		new SpellCard("想起「恐怖的回忆」", "古明地觉", 15),
		new SpellCard("想起「恐怖催眠术」", "古明地觉", 15),
		new SpellCard("想起「二重黑死蝶」", "古明地觉", 15),
		new SpellCard("想起「飞行虫之巢」", "古明地觉", 15),
		new SpellCard("想起「波与粒的境界」", "古明地觉", 15),
		new SpellCard("想起「户隐山之投」", "古明地觉", 15),
		new SpellCard("想起「百万鬼夜行」", "古明地觉", 15),
		new SpellCard("想起「蒙蒙迷雾」", "古明地觉", 15),
		new SpellCard("想起「风神木叶隐身术」", "古明地觉", 15),
		new SpellCard("想起「天狗巨暴流」", "古明地觉", 15),
		new SpellCard("想起「鸟居旋风」", "古明地觉", 15),
		new SpellCard("想起「春之京人偶」", "古明地觉", 15),
		new SpellCard("想起「稻草人敢死队」", "古明地觉", 15),
		new SpellCard("想起「回归虚无」", "古明地觉", 15),
		new SpellCard("想起「水银之毒」", "古明地觉", 15),
		new SpellCard("想起「水精公主」", "古明地觉", 15),
		new SpellCard("想起「贤者之石」", "古明地觉", 15),
		new SpellCard("想起「延展手臂」", "古明地觉", 15),
		new SpellCard("想起「河童之河口浪潮」", "古明地觉", 15),
		new SpellCard("想起「粼粼水底之心伤」", "古明地觉", 15),
		new SpellCard("猫符「猫的步伐」", "火焰猫燐", 3),
		new SpellCard("猫符「怨灵猫乱步」", "火焰猫燐", 12),
		new SpellCard("咒精「僵尸妖精」", "火焰猫燐", 3),
		new SpellCard("咒精「怨灵凭依妖精」", "火焰猫燐", 12),
		new SpellCard("恨灵「脾脏蛀食者」", "火焰猫燐", 3),
		new SpellCard("尸灵「食人怨灵」", "火焰猫燐", 12),
		new SpellCard("赎罪「旧地狱的针山」", "火焰猫燐", 3),
		new SpellCard("赎罪「古时之针与痛楚的怨灵」", "火焰猫燐", 12),
		new SpellCard("「死灰复燃」", "火焰猫燐", 3),
		new SpellCard("「小恶灵复活」", "火焰猫燐", 12),
		new SpellCard("妖怪「火焰的车轮」", "火焰猫燐", 15),
		new SpellCard("核热「核聚变」", "灵乌路空", 3),
		new SpellCard("核热「核功率骤增」", "灵乌路空", 4),
		new SpellCard("核热「核反应失控」", "灵乌路空", 8),
		new SpellCard("爆符「小型耀斑」", "灵乌路空", 1),
		new SpellCard("爆符「百万耀斑」", "灵乌路空", 2),
		new SpellCard("爆符「十亿耀斑」", "灵乌路空", 4),
		new SpellCard("爆符「千兆耀斑」", "灵乌路空", 8),
		new SpellCard("焰星「恒星」", "灵乌路空", 3),
		new SpellCard("焰星「行星公转」", "灵乌路空", 4),
		new SpellCard("焰星「十凶星」", "灵乌路空", 8),
		new SpellCard("「地狱极乐熔毁」", "灵乌路空", 3),
		new SpellCard("「地狱的托卡马克」", "灵乌路空", 12),
		new SpellCard("「地狱的人工太阳」", "灵乌路空", 3),
		new SpellCard("「地底太阳」", "灵乌路空", 12),
		new SpellCard("秘法「九字切」", "东风谷早苗", 16),
		new SpellCard("奇迹「神秘果」", "东风谷早苗", 16),
		new SpellCard("神德「五谷丰穰米之浴」", "东风谷早苗", 16),
		new SpellCard("表象「先祖托梦」", "古明地恋", 16),
		new SpellCard("表象「弹幕偏执症」", "古明地恋", 16),
		new SpellCard("本能「本我的解放」", "古明地恋", 16),
		new SpellCard("抑制「超我」", "古明地恋", 16),
		new SpellCard("反应「妖怪测谎机」", "古明地恋", 16),
		new SpellCard("潜意识「弹幕的墨迹测验」", "古明地恋", 16),
		new SpellCard("复燃「恋爱的埋火」", "古明地恋", 16),
		new SpellCard("深层「潜意识的基因」", "古明地恋", 16),
		new SpellCard("「被厌恶者的哲学」", "古明地恋", 16),
		new SpellCard("「地底蔷薇」", "古明地恋", 16)
	};
}
