package com.meng.config;

public enum NetworkType {
    addGroup,
    addNotReplyUser,
    addNotReplyWord,
    addPersonInfo,
    addMaster,
    addAdmin,
    addGroupAllow,
    addBlackQQ,
    addBlackGroup,
    removeGroup,
    removeNotReplyUser,
    removeNotReplyWord,
    removePersonInfo,
    removeMaster,
    removeAdmin,
    removeGroupAllow,
    removeBlackQQ,
    removeBlackGroup,
    setGroup,
    setNotReplyUser,
    setNotReplyWord,
    setPersonInfo,
    setMaster,
    setAdmin,
    setGroupAllow,
    setBlackQQ,
    setBlackGroup,
}
