import m.*;

public class Main {
	public static void main(String[] args) {
		SpellCardBuilder scb=new SpellCardBuilder()
			.setMaster("秋静叶")
			.addSpell("叶符「狂舞的落叶」", 2, 3)

			.setMaster("秋穰子")
			.addSpell("秋符「秋季的天空」", 0, 1)
			.addSpell("秋符「无常秋日与少女的心」", 2, 3)
			.addSpell("丰符「大年收获者」",  0, 1)
			.addSpell("丰收「谷物神的允诺」", 2, 3)

			.setMaster("键山雏")
			.addSpell("厄符「厄运」", 0, 1)
			.addSpell("厄符「厄神大人的生理节律」", 2, 3)
			.addSpell("疵符「破裂的护符」", 0, 1)
			.addSpell("疵痕「损坏的护身符」", 2, 3)
			.addSpell("恶灵「厄运之轮」", 0, 1)
			.addSpell("悲运「大钟婆之火」", 2, 3)
			.addSpell("创符「痛苦之流」", 0, 1)
			.addSpell("创符「流刑人偶」", 2, 3)

			.setMaster("河城荷取")
			.addSpell("光学「光学迷彩」", 0, 1)
			.addSpell("光学「水迷彩」", 2, 3)
			.addSpell("洪水「泥浆泛滥」", 0, 1)
			.addSpell("洪水「冲积梦魇」", 2)
			.addSpell("漂溺「粼粼水底之心伤」", 3)
			.addSpell("水符「河童之河口浪潮」", 0, 1)
			.addSpell("水符「河童之山洪暴发」", 2)
			.addSpell("水符「河童之幻想大瀑布」", 3)
			.addSpell("河童「妖怪黄瓜」", 0, 1)
			.addSpell("河童「延展手臂」", 2)
			.addSpell("河童「回转顶板」", 3)

			.setMaster("射命丸文")
			.addSpell("岐符「天之八衢」", 0, 1)
			.addSpell("岐符「猿田彦神之岔路」", 2, 3)
			.addSpell("风神「风神木叶隐身术」", 0, 1)
			.addSpell("风神「天狗颪」", 2)
			.addSpell("风神「二百十日」", 3)
			.addSpell("「幻想风靡」", 1, 2)
			.addSpell("「无双风神」", 3)
			.addSpell("塞符「山神渡御」", 0, 1)
			.addSpell("塞符「天孙降临」", 2)
			.addSpell("塞符「天上天下的照国」", 3)

			.setMaster("东风谷早苗")
			.addSpell("秘术「灰色奇术」", 0, 1)
			.addSpell("秘术「遗忘之祭仪」", 2)
			.addSpell("秘术「一脉相传的弹幕」", 3)
			.addSpell("奇迹「白昼的客星」", 0, 1)
			.addSpell("奇迹「客星璀璨之夜」", 2)
			.addSpell("奇迹「客星辉煌之夜」", 3)
			.addSpell("开海「割海成路之日」", 0, 1)
			.addSpell("开海「摩西之奇迹」", 2, 3)
			.addSpell("准备「呼唤神风的星之仪式」", 0, 1)
			.addSpell("准备「召请建御名方神」", 2, 3)
			.addSpell("奇迹「神之风」", 0, 1)
			.addSpell("大奇迹「八坂之神风」", 2, 3)

			.setMaster("八坂神奈子")
			.addSpell("神祭「扩展御柱」", 0, 1)
			.addSpell("奇祭「目处梃子乱舞」", 2, 3)
			.addSpell("筒粥「神の粥」", 0, 1)
			.addSpell("忘谷「遗忘之谷」", 2)
			.addSpell("神谷「神谕之谷」", 3)
			.addSpell("贽符「御射山御狩神事」", 0, 1)
			.addSpell("神秘「葛泉清水」", 2)
			.addSpell("神秘「大和茅环」", 3)
			.addSpell("天流「天水奇迹」", 0, 1)
			.addSpell("天龙「雨之源泉」", 2, 3)
			.addSpell("「信仰之山」", 0, 1)
			.addSpell("「风神之神德」", 2, 3)
			.addSpell("神符「如水眼之美丽源泉」", 4)
			.addSpell("神符「结于杉木之古缘」", 4)
			.addSpell("神符「神所踏足之御神渡」", 4)

			.setMaster("洩矢诹访子")
			.addSpell("开宴「二拜二拍一拜」", 4)
			.addSpell("土著神「手长足长大人」", 4)
			.addSpell("神具「洩矢的铁轮」", 4)
			.addSpell("源符「厌川的翡翠」", 4)
			.addSpell("蛙狩「蛙以口鸣，方致蛇祸」", 4)
			.addSpell("土著神「七石七木」", 4)
			.addSpell("土著神「小小青蛙不输风雨」", 4)
			.addSpell("土著神「宝永四年的赤蛙」", 4)
			.addSpell("「诹访大战 ~ 土著神话 vs 中央神话」", 4)
			.addSpell("祟符「洩矢大人」", 4);

		System.out.println(scb.getSpell());
	}
}
