import m.*;

public class Main {
	public static void main(String[] args) {
		SpellCardBuilder scb=new SpellCardBuilder()
			.setMaster("纳兹琳")
			.addSpell("棒符「忙碌探知棒」", 2, 3)
			.addSpell("搜符「稀有金属探测器」", 0, 1)
			.addSpell("搜符「G黄金探测器」", 2, 3)
			.addSpell("视符「娜兹玲灵摆」", 0, 1)
			.addSpell("视符「高感度娜兹玲灵摆」", 2)
			.addSpell("守符「灵摆防御」", 3)

			.setMaster("多多良小伞")
			.addSpell("大轮「唐伞光晕」",  0, 1)
			.addSpell("大轮「Hello,Forgotten World」", 2, 3)
			.addSpell("伞符「雨伞的星之交响」", 0, 1)
			.addSpell("伞符「雨伞的星之追忆」", 2, 3)
			.addSpell("雨符「雨夜怪谈」", 0, 1)
			.addSpell("雨伞「超防水干爽伞妖」", 2, 3)
			.addSpell("化符「遗忘之伞的夜行列车」", 0, 1)
			.addSpell("化铁「备用伞特急夜晚狂欢号」", 2, 3)

			.setMaster("云居一轮")
			.addSpell("铁拳「问答无用妖怪拳」",  0, 1)
			.addSpell("神拳「凌云地狱冲」", 2)
			.addSpell("神拳「天海地狱冲」", 3)
			.addSpell("拳符「天网沙袋」", 0, 1)
			.addSpell("连打「云界海妖来袭」", 2)
			.addSpell("连打「帝王海妖来袭」", 3)
			.addSpell("拳打「重拳碎击」", 0, 1)
			.addSpell("溃灭「天上天下连续勾拳」", 2, 3)
			.addSpell("大喝「守旧尊老之怒眼」", 0, 1)
			.addSpell("忿怒「天变巨眼焚身」", 2)
			.addSpell("忿怒「空前绝后巨眼焚身」", 3)

			.setMaster("村纱水蜜")
			.addSpell("倾覆「同路人之锚」", 0, 1)
			.addSpell("倾覆「沉没之锚」", 2)
			.addSpell("倾覆「击沉之锚」", 3)
			.addSpell("溺符「深海漩涡」", 0, 1)
			.addSpell("溺符「沉底漩涡」", 2, 3)
			.addSpell("港符「幽灵船之泊」", 0, 1)
			.addSpell("港符「幽灵船之港」", 2)
			.addSpell("港符「幽灵船永久停泊」", 3)
			.addSpell("幽灵「Sinker Ghost」", 1)
			.addSpell("幽灵「悄然袭来的长勺」", 2, 3)

			.setMaster("纳兹琳")
			.addSpell("宝塔「最优良的宝物」", 0, 1, 2, 3)

			.setMaster("寅丸星")
			.addSpell("宝塔「光辉之宝」", 0, 1)
			.addSpell("宝塔「光辉宝枪」", 2, 3)
			.addSpell("光符「绝对正义」", 0, 1)
			.addSpell("光符「正义之威光」", 2, 3)
			.addSpell("法力「至宝之独钴杵」", 0, 1)
			.addSpell("法灯「无瑕佛法之独钴杵」", 2, 3)
			.addSpell("光符「净化之魔」", 0, 1, 2)
			.addSpell("「完全净化」", 3)

			.setMaster("圣白莲")
			.addSpell("魔法「紫云之兆」", 0, 1)
			.addSpell("吉兆「紫色云路」", 2)
			.addSpell("吉兆「极乐的紫色云路」", 3)
			.addSpell("魔法「魔界蝶之妖香」", 0, 1)
			.addSpell("魔法「魔法之蝶」", 2, 3)
			.addSpell("光魔「星辰漩涡」", 0, 1)
			.addSpell("光魔「魔法银河」", 2, 3)
			.addSpell("大魔法「魔神复诵」", 0, 1, 2, 3)
			.addSpell("「圣尼公的气之魔法卷轴」", 1, 2)
			.addSpell("超人「圣白莲」", 3)
			.addSpell("飞钵「飞行幻想」", 0, 1)
			.addSpell("飞钵「传说的飞空圆盘」", 2, 3)

			.setMaster("多多良小伞")
			.addSpell("伞符「大颗的泪雨」", 4)
			.addSpell("惊雨「台风骤雨」", 4)
			.addSpell("光晕「唐伞惊吓闪光」", 4)
			
			.setMaster("封兽鵺")
			.addSpell("妖云「平安时代的黑云」", 4)
			.addSpell("真相不明「愤怒的红色UFO袭来」", 4)
			.addSpell("鵺符「鵺的蛇行表演」", 4)
			.addSpell("真相不明「哀愁的蓝色UFO袭来」", 4)
			.addSpell("鵺符「弹幕奇美拉」", 4)
			.addSpell("真相不明「忠义的绿色UFO袭来」", 4)
			.addSpell("鵺符「真相不明的黑暗」", 4)
			.addSpell("真相不明「恐怖的虹色UFO袭来」",  4)
			.addSpell("「平安京的恶梦」", 4)
			.addSpell("恨弓「源三位赖政之弓」", 4);

		System.out.println(scb.getSpell());
	}
}
