import m.*;

public class Main {
	public static void main(String[] args) {
		SpellCardBuilder scb=new SpellCardBuilder()
			.setMaster("西行寺幽幽子")
			.addSpell("符牒「死蝶之舞」", 0, 1)
			.addSpell("符牒「死蝶之舞 -樱花-」", 2, 3)
			.addSpell("幽蝶「幽魂聚地」", 0, 1)
			.addSpell("幽蝶「幽魂聚地 -樱花-」", 2, 3)
			.addSpell("冥符「常夜樱」", 0, 1, 2, 3)
			.addSpell("樱符「西行樱吹雪」", 2, 3)
			.addSpell("樱符「樱吹雪地狱」", 8)

			.setMaster("幽谷响子")
			.addSpell("响符「山谷回声」", 0, 1)
			.addSpell("响符「混乱的山谷回声」", 2, 3)
			.addSpell("响符「强力共振」", 0, 1, 2, 3)
			.addSpell("山彦「远距离回声」", 0, 1)
			.addSpell("山彦「扩大回声」", 2, 3)
			.addSpell("大声「激动的呼喊」",  0, 1)
			.addSpell("大声「激动Yahoo」", 2, 3)
			.addSpell("山彦「山彦的发挥本领之回音」", 8)

			.setMaster("多多良小伞")
			.addSpell("虹符「雨伞风暴」",  2, 3)

			.setMaster("宫古芳香")
			.addSpell("回复「借由欲望的恢复」", 0, 1, 2, 3)
			.addSpell("毒爪「剧毒抹消」", 0, 1)
			.addSpell("毒爪「剧毒杀害」", 2, 3)
			.addSpell("欲符「赚钱欲灵招来」", 0, 1)
			.addSpell("欲灵「贪分欲吞噬者」", 2, 3)
			.addSpell("毒爪「不死的杀人鬼」", 8)

			.setMaster("霍青娥")
			.addSpell("邪符「养小鬼」", 1)
			.addSpell("邪符「孤魂野鬼」", 2, 3)
			.addSpell("入魔「走火入魔」", 0, 1, 2, 3)
			.addSpell("降灵「死人童乩」", 0, 1)
			.addSpell("通灵「通灵芳香」", 2, 3)
			.addSpell("道符「道胎动」", 0, 1, 2, 3)
			.addSpell("道符「TAO胎动 ~道~」", 8)

			.setMaster("苏我屠自古")
			.addSpell("雷矢「元兴寺的旋风」", 1, 2)
			.addSpell("雷矢「元兴寺的龙卷」", 3)
			.addSpell("怨灵「入鹿之雷」", 8)

			.setMaster("物部布都")
			.addSpell("天符「雨之磐舟」", 0, 1)
			.addSpell("天符「天之磐舟哟，向天飞升吧」", 2, 3)
			.addSpell("投皿「物部氏的八十平瓮」", 0, 1, 2, 3)
			.addSpell("炎符「废佛之炎风」", 0, 1)
			.addSpell("炎符「火烧樱井寺」", 2, 3)
			.addSpell("圣童女「大物忌正餐」", 0, 1, 2, 3)
			.addSpell("圣童女「太阳神的贡品」", 8)

			.setMaster("丰聪耳神子")
			.addSpell("名誉「十二阶之色彩」", 0, 1)
			.addSpell("名誉「十二阶之冠位」", 2, 3)
			.addSpell("仙符「日出之处的道士」", 0, 1)
			.addSpell("仙符「日出之处的天子」", 2, 3)
			.addSpell("召唤「豪族乱舞」", 0, 1, 2, 3)
			.addSpell("秘宝「斑鸠寺的天球仪」", 0, 1, 2)
			.addSpell("秘宝「圣德太子的欧帕兹」", 3)
			.addSpell("光符「救世观音的佛光」", 0, 1)
			.addSpell("光符「救世之光」", 2, 3)
			.addSpell("眼光「十七条的光芒」", 0, 1)
			.addSpell("神光「无忤为宗」", 2, 3)
			.addSpell("「星辰降落的神灵庙」", 0, 1)
			.addSpell("「新生的神灵」", 2, 3)
			.addSpell("「神灵大宇宙」", 8)

			.setMaster("封兽鵺")
			.addSpell("未知「轨道不明的鬼火」", 4)
			.addSpell("未知「姿态不明的空鱼」", 4)
			.addSpell("未知「原理不明的妖怪玉」", 4)

			.setMaster("二岩瑞藏")
			.addSpell("一回胜负「灵长类弹幕变化」", 4)
			.addSpell("二回胜负「肉食类弹幕变化」", 4)
			.addSpell("三回胜负「羽鸟类弹幕变化」", 4)
			.addSpell("四回胜负「两栖类弹幕变化」", 4)
			.addSpell("五回胜负「鸟兽戏画」", 4)
			.addSpell("六回胜负「狸猫的变身学校」",  4)
			.addSpell("七回胜负「野生的离岛」", 4)
			.addSpell("变化「魔奴化巫女的伪退治」", 4)
			.addSpell("「猯藏化弹幕十变化」", 4)
			.addSpell("貉符「满月下的腹鼓舞」", 4)
			.addSpell("「Wild Carpet」", 8);
		System.out.println(scb.getSpell());
	}
}
