import m.*;

public class Main {
	public static void main(String[] args) {
		SpellCardBuilder scb=new SpellCardBuilder()
			.setMaster("秋静叶")

			.setMaster("琪斯美")
			.addSpell("怪奇「钓瓶落之怪」", 2, 3)

			.setMaster("黑谷山女")
			.addSpell("罠符「捕捉之网」", 0, 1)
			.addSpell("蜘蛛「石窟的蜘蛛巢」", 2, 3)
			.addSpell("瘴符「瘴气场」", 0, 1)
			.addSpell("瘴气「原因不明的热病」", 2, 3)

			.setMaster("水桥帕露西")
			.addSpell("妒符「绿眼怪兽」", 0, 1)
			.addSpell("嫉妒「看不见的绿眼怪兽」", 2, 3)
			.addSpell("开花爷爷「对华丽的仁者之嫉妒」", 0, 1)
			.addSpell("开花爷爷「小白的灰烬」", 2, 3)
			.addSpell("剪舌麻雀「对谦虚的富者之记恨」", 0, 1)
			.addSpell("剪舌麻雀「大葛笼与小葛笼」", 2, 3)
			.addSpell("恨符「丑时参拜」", 0, 1)
			.addSpell("恨符「丑时参拜第七日」", 2, 3)

			.setMaster("星熊勇仪")
			.addSpell("鬼符「怪力乱神」", 0, 1, 2, 3)
			.addSpell("怪轮「地狱之苦轮」", 0, 1)
			.addSpell("枷符「罪人不释之枷」", 2, 3)
			.addSpell("力业「大江山岚」", 0, 1)
			.addSpell("力业「大江山颪」", 2, 3)
			.addSpell("四天王奥义「三步必杀」", 0, 1, 2, 3)

			.setMaster("古明地觉")
			.addSpell("想起「恐怖的回忆」", 0, 1, 2, 3)
			.addSpell("想起「恐怖催眠术」", 0, 1, 2, 3)
			.addSpell("想起「二重黑死蝶」", 0, 1, 2, 3)
			.addSpell("想起「飞行虫之巢」", 0, 1, 2, 3)
			.addSpell("想起「波与粒的境界」", 0, 1, 2, 3)
			.addSpell("想起「户隐山之投」", 0, 1, 2, 3)
			.addSpell("想起「百万鬼夜行」", 0, 1, 2, 3)
			.addSpell("想起「蒙蒙迷雾」", 0, 1, 2, 3)
			.addSpell("想起「风神木叶隐身术」", 0, 1, 2, 3)
			.addSpell("想起「天狗巨暴流」", 0, 1, 2, 3)
			.addSpell("想起「鸟居旋风」", 0, 1, 2, 3)
			.addSpell("想起「春之京人偶」", 0, 1, 2, 3)
			.addSpell("想起「稻草人敢死队」", 0, 1, 2, 3)
			.addSpell("想起「回归虚无」", 0, 1, 2, 3)
			.addSpell("想起「水银之毒」", 0, 1, 2, 3)
			.addSpell("想起「水精公主」", 0, 1, 2, 3)
			.addSpell("想起「贤者之石」", 0, 1, 2, 3)
			.addSpell("想起「延展手臂」", 0, 1, 2, 3)
			.addSpell("想起「河童之河口浪潮」", 0, 1, 2, 3)
			.addSpell("想起「粼粼水底之心伤」", 0, 1, 2, 3)

			.setMaster("火焰猫燐")
			.addSpell("猫符「猫的步伐」", 0, 1)
			.addSpell("猫符「怨灵猫乱步」", 2, 3)
			.addSpell("咒精「僵尸妖精」", 0, 1)
			.addSpell("咒精「怨灵凭依妖精」", 2, 3)
			.addSpell("恨灵「脾脏蛀食者」", 0, 1)
			.addSpell("尸灵「食人怨灵」", 2, 3)
			.addSpell("赎罪「旧地狱的针山」", 0, 1)
			.addSpell("赎罪「古时之针与痛楚的怨灵」", 2, 3)
			.addSpell("「死灰复燃」", 0, 1)
			.addSpell("「小恶灵复活」", 2, 3)
			.addSpell("妖怪「火焰的车轮」", 0, 1, 2, 3)

			.setMaster("灵乌路空")
			.addSpell("核热「核聚变」", 0, 1)
			.addSpell("核热「核功率骤增」", 2)
			.addSpell("核热「核反应失控」", 3)
			.addSpell("爆符「小型耀斑」", 0)
			.addSpell("爆符「百万耀斑」", 1)
			.addSpell("爆符「十亿耀斑」", 2)
			.addSpell("爆符「千兆耀斑」", 3)
			.addSpell("焰星「恒星」", 0, 1)
			.addSpell("焰星「行星公转」", 2)
			.addSpell("焰星「十凶星」", 3)
			.addSpell("「地狱极乐熔毁」", 0, 1)
			.addSpell("「地狱的托卡马克」", 2, 3)
			.addSpell("「地狱的人工太阳」", 0, 1)
			.addSpell("「地底太阳」", 2, 3)

			.setMaster("东风谷早苗")
			.addSpell("秘法「九字切」", 4)
			.addSpell("奇迹「神秘果」", 4)
			.addSpell("神德「五谷丰穰米之浴」", 4)

			.setMaster("古明地恋")
			.addSpell("表象「先祖托梦」", 4)
			.addSpell("表象「弹幕偏执症」", 4)
			.addSpell("本能「本我的解放」", 4)
			.addSpell("抑制「超我」", 4)
			.addSpell("反应「妖怪测谎机」", 4)
			.addSpell("潜意识「弹幕的墨迹测验」", 4)
			.addSpell("复燃「恋爱的埋火」", 4)
			.addSpell("深层「潜意识的基因」", 4)
			.addSpell("「被厌恶者的哲学」", 4)
			.addSpell("「地底蔷薇」", 4);


		System.out.println(scb.getSpell());
	}
}
