import m.*;

public class Main {
	public static void main(String[] args) {
		SpellCardBuilder scb=new SpellCardBuilder()
			.setMaster("莉格露·奈特巴格")
			.addSpell("萤符「地上的流星」", 2)
			.addSpell("萤符「地上的彗星」", 3)
			.addSpell("灯符「萤光现象」", 0, 1, 2, 3)
			.addSpell("蠢符「小虫」", 0)
			.addSpell("蠢符「小虫风暴」", 1)
			.addSpell("蠢符「夜虫风暴」", 2)
			.addSpell("蠢符「夜虫龙卷」",  3)
			.addSpell("隐虫「永夜蛰居」", 6)

			.setMaster("米斯蒂娅·萝蕾拉")
			.addSpell("声符「枭的夜鸣声」", 0, 1)
			.addSpell("声符「木菟的咆哮」", 2, 3)
			.addSpell("蛾符「天蛾的蛊道」", 0, 1)
			.addSpell("毒符「毒蛾的鳞粉」", 2)
			.addSpell("猛毒「毒蛾的黑暗演舞」",  3)
			.addSpell("鹰符「祸延疾冲」", 0, 1, 2, 3)
			.addSpell("夜盲「夜雀之歌」", 0, 1, 2, 3)
			.addSpell("夜雀「午夜的合唱指挥」", 6)

			.setMaster("上白泽慧音")
			.addSpell("产灵「最初的金字塔」", 0, 1, 2, 3)
			.addSpell("始符「短暂的137」", 1, 2, 3)
			.addSpell("野符「武烈的危机」", 0)
			.addSpell("野符「将门的危机」", 1)
			.addSpell("野符「义满的危机」", 2)
			.addSpell("野符「GHQ的危机」", 3)
			.addSpell("国符「三种神器 剑」", 0)
			.addSpell("国符「三种神器 玉」", 1)
			.addSpell("国符「三种神器 镜」", 2)
			.addSpell("国体「三种神器 乡」", 3)
			.addSpell("终符「幻想天皇」", 0, 1)
			.addSpell("虚史「幻想乡传说」", 2, 3)
			.addSpell("未来「高天原」", 6)

			.setMaster("博丽灵梦")
			.addSpell("梦符「二重结界」",  0, 1)
			.addSpell("梦境「二重大结界」", 2, 3)
			.addSpell("灵符「梦想封印 散」", 0, 1)
			.addSpell("散灵「梦想封印 寂」", 2, 3)
			.addSpell("梦符「封魔阵」", 0, 1)
			.addSpell("神技「八方鬼缚阵」", 2)
			.addSpell("神技「八方龙杀阵」", 3)
			.addSpell("灵符「梦想封印 集」", 0, 1)
			.addSpell("回灵「梦想封印 侘」", 2, 3)
			.addSpell("境界「二重弹幕结界」", 0, 1)
			.addSpell("大结界「博丽弹幕结界」", 2, 3)
			.addSpell("神灵「梦想封印 瞬」", 6)

			.setMaster("雾雨魔理沙")
			.addSpell("魔符「银河」", 0, 1)
			.addSpell("魔空「小行星带」", 2, 3)
			.addSpell("魔符「星尘幻想」", 0, 1)
			.addSpell("黑魔「黑洞边缘」", 2, 3)
			.addSpell("恋符「非定向光线」", 0, 1)
			.addSpell("恋风「星光台风」", 2, 3)
			.addSpell("恋符「极限火花」", 0, 1)
			.addSpell("恋心「二重火花」", 2, 3)
			.addSpell("光符「地球光」", 0, 1)
			.addSpell("光击「击月」", 2, 3)
			.addSpell("魔炮「Final Spark」", 6)
			.addSpell("魔炮「Final Master Spark」", 6)

			.setMaster("铃仙·优昙华院·因幡")
			.addSpell("波符「赤眼催眠(Mind Shaker)」", 0, 1)
			.addSpell("幻波「赤眼催眠(Mind Blowing)」", 2, 3)
			.addSpell("狂符「幻视调律(Visionary Tuning)」", 0, 1)
			.addSpell("狂视「狂视调律(Illusion Seeker)」", 2, 3)
			.addSpell("懒符「生神停止(Idling Wave)」", 0, 1)
			.addSpell("懒惰「生神停止(Mind Stopper)」", 2, 3)
			.addSpell("散符「真实之月(Invisible Full Moon)」", 0, 1, 2, 3)
			.addSpell("月眼「月兔远隔催眠术(Tele-Mesmerism)」", 6)

			.setMaster("八意永琳")
			.addSpell("天丸「壶中的天地」", 0, 1, 2, 3)
			.addSpell("觉神「神代的记忆」", 0, 1)
			.addSpell("神符「天人的族谱」", 2, 3)
			.addSpell("苏活「生命游戏 -Life Game-」", 0, 1)
			.addSpell("苏生「Rising Game」", 2, 3)
			.addSpell("操神「思兼装置」", 0, 1)
			.addSpell("神脑「思兼的头脑」", 2, 3)
			.addSpell("天咒「阿波罗13」", 0, 1, 2, 3)
			.addSpell("秘术「天文密葬法」", 0, 1, 2, 3)
			.addSpell("禁药「蓬莱之药」", 6)
			.addSpell("药符「壶中的大银河」", 0, 1, 2, 3)

			.setMaster("蓬莱山辉夜")
			.addSpell("难题「龙颈之玉 -五色的弹丸-」", 0, 1)
			.addSpell("神宝「耀眼的龙玉」", 2, 3)
			.addSpell("难题「佛御石之钵 -不碎的意志-」", 0, 1)
			.addSpell("神宝「佛体的金刚石」", 2, 3)
			.addSpell("难题「火鼠的皮衣 -不焦躁的内心-」", 0, 1)
			.addSpell("神宝「火蜥蜴之盾」", 2, 3)
			.addSpell("难题「燕的子安贝 -永命线-」", 0, 1)
			.addSpell("神宝「无限的生命之泉」", 2, 3)
			.addSpell("难题「蓬莱的弹枝 -七色的弹幕-」", 0, 1)
			.addSpell("神宝「蓬莱的玉枝 -梦色之乡-」", 2, 3)
			.addSpell("「永夜返 -初月-」", 6)
			.addSpell("「永夜返 -新月-」", 6)
			.addSpell("「永夜返 -上弦月-」", 6)
			.addSpell("「永夜返 -待宵-」", 6)
			.addSpell("「永夜返 -子之刻-」", 6)
			.addSpell("「永夜返 -子时二刻-」", 6)
			.addSpell("「永夜返 -子时三刻-」", 6)
			.addSpell("「永夜返 -子时四刻-」", 6)
			.addSpell("「永夜返 -丑之刻-」", 6)
			.addSpell("「永夜返 -丑时二刻-」", 6)
			.addSpell("「永夜返 -丑时三刻-」", 6)
			.addSpell("「永夜返 -丑时四刻-」", 6)
			.addSpell("「永夜返 -寅之刻-」", 6)
			.addSpell("「永夜返 -寅时二刻-」", 6)
			.addSpell("「永夜返 -寅时三刻-」", 6)
			.addSpell("「永夜返 -寅时四刻-」", 6)
			.addSpell("「永夜返 -朝霭-」", 6)
			.addSpell("「永夜返 -拂晓-」", 6)
			.addSpell("「永夜返 -耀世的启明星-」", 6)
			.addSpell("「永夜返 -光明之世-」", 6)

			.setMaster("上白泽慧音")
			.addSpell("旧史「旧秘境史 -古代史-」", 4)
			.addSpell("转世「一条归桥」", 4)
			.addSpell("新史「新幻想史 -现代史-」", 4)

			.setMaster("藤原妹红")
			.addSpell("时效「月岩笠的诅咒」",  4)
			.addSpell("不死「火鸟 -凤翼天翔-」", 4)
			.addSpell("藤原「灭罪寺院伤」", 4)
			.addSpell("不死「徐福时空」", 4)
			.addSpell("灭罪「正直者之死」", 4)
			.addSpell("虚人「无一」", 4)
			.addSpell("不灭「不死鸟之尾」", 4)
			.addSpell("蓬莱「凯风快晴 -Fujiyama Volcano-」", 4)
			.addSpell("「不死鸟附体」", 4)
			.addSpell("「蓬莱人形」", 4)
			.addSpell("「不朽的弹幕」", 6)

			.setMaster("莉格露·奈特巴格")
			.addSpell("「不合时令的蝶雨」", 7)

			.setMaster("米斯蒂娅·萝蕾拉")
			.addSpell("「失明的夜雀」", 7)

			.setMaster("上白泽慧音")
			.addSpell("「日出之国的天子」", 7)
			.addSpell("「似有似无的净化」", 7)

			.setMaster("因幡帝")
			.addSpell("「Ancient Duper」", 7)

			.setMaster("铃仙·优昙华院·因幡")
			.addSpell("「幻胧月睨（Lunatic Red Eyes）」", 7)

			.setMaster("八意永琳")
			.addSpell("「天网蛛网捕蝶之法」", 7)

			.setMaster("蓬莱山辉夜")
			.addSpell("「蓬莱的树海」", 7)

			.setMaster("藤原妹红")
			.addSpell("「不死鸟重生」", 7)

			.setMaster("博丽灵梦")
			.addSpell("「梦想天生」", 7)

			.setMaster("雾雨魔理沙")
			.addSpell("「Blazing Star」", 7)

			.setMaster("十六夜咲夜")
			.addSpell("「收缩的世界」", 7)

			.setMaster("魂魄妖梦")
			.addSpell("「待宵反射卫星斩」", 7)

			.setMaster("爱丽丝·玛格特罗依德")
			.addSpell("「猎奇剧团的怪人」", 7)

			.setMaster("蕾米莉亚·斯卡雷特")
			.addSpell("「绯红的宿命」", 7)

			.setMaster("西行寺幽幽子")
			.addSpell("「西行寺无余涅槃」", 7)

			.setMaster("八云紫")
			.addSpell("「深弹幕结界 梦幻泡影」", 7);


		System.out.println(scb.getSpell());
	}
}
