package com.meng.gameData.TouHou.zun;
import com.meng.gameData.TouHou.*;

public class TH07GameData {
	public static final String gameName="东方妖妖梦 ~ Perfect Cherry Blossom.";
	public static final String gameNameCN="东方妖妖梦";
	public static final String gameNameAbbr="PCB";
	public static String[] players = new String[]{"博丽灵梦 灵符", "博丽灵梦 梦符", "雾雨魔理沙 魔符", "雾雨魔理沙 恋符", "十六夜咲夜 幻符", "十六夜咲夜 时符"};
	public static String[] charaName=new String[]{
		"蕾蒂·霍瓦特洛克",
		"橙",
		"爱丽丝·玛格特罗依德",
		"莉莉白",
		"莉莉卡·普莉兹姆利巴", 
		"梅露兰·普莉兹姆利巴",
		"露娜萨·普莉兹姆利巴",
		"魂魄妖梦",
		"西行寺幽幽子",
		"八云蓝",
		"八云紫"
	};
	public static String[] musicName=new String[]{
		"妖妖梦 ~ Snow or Cherry Petal",
		"无何有之乡 ~ Deep Mountain",
		"Crystallize Silver",
		"远野幻想物语",
		"凋叶棕（withered leaf）",
		"布加勒斯特的人偶师",
		"人偶裁判 ~ 玩弄人形的少女",
		"天空的花都",
		"幽灵乐团 ~ Phantom Ensemble",
		"东方妖妖梦 ~ Ancient Temple",
		"广有射怪鸟事 ~ Till When?",
		"Ultimate Truth",
		"幽雅地绽放吧，墨染的樱花 ~ Border of Life",
		"Border of Life",
		"妖妖跋扈",
		"少女幻葬 ~ Necro-Fantasy",
		"妖妖跋扈 ~ Who done it!",
		"Necro-Fantasia",	
		"春风之梦",
		"樱花樱花 ~ Japanize Dream..."
	};
	public static SpellCard[] spellcards=new SpellCard[]{
		new SpellCard("冰符「冰袭方阵」", "琪露诺", SpellCard.H | SpellCard.L),
		new SpellCard("寒符「延长的冬日」", "蕾蒂·霍瓦特洛克", SpellCard.E | SpellCard.N | SpellCard.H | SpellCard.L),
		new SpellCard("冬符「花之凋零」", "蕾蒂·霍瓦特洛克", SpellCard.E | SpellCard.N),
		new SpellCard("白符「波状光」", "蕾蒂·霍瓦特洛克", SpellCard.H),
		new SpellCard("怪符「桌灵转」", "蕾蒂·霍瓦特洛克", SpellCard.L),
		new SpellCard("仙符「凤凰卵」", "橙", SpellCard.E | SpellCard.N),
		new SpellCard("仙符「凤凰展翅」", "橙", SpellCard.H | SpellCard.L),
		new SpellCard("式符「飞翔晴明」", "橙", SpellCard.E | SpellCard.N),
		new SpellCard("阴阳「道满晴明」", "橙", SpellCard.H),
		new SpellCard("阴阳「晴明大纹」", "橙", SpellCard.L),
		new SpellCard("天符「天仙鸣动」", "橙", SpellCard.E | SpellCard.N),
		new SpellCard("翔符「飞翔韦驮天」", "橙", SpellCard.H),
		new SpellCard("童符「护法天童乱舞」", "橙", SpellCard.L),
		new SpellCard("仙符「尸解永远」", "橙", SpellCard.E | SpellCard.N),
		new SpellCard("鬼符「鬼门金神」", "橙", SpellCard.H),
		new SpellCard("方符「奇门遁甲」", "橙", SpellCard.L),
		new SpellCard("鬼符「青鬼赤鬼」", "橙", SpellCard.Ex),
		new SpellCard("鬼神「飞翔毘沙门天」", "橙", SpellCard.Ex),
		new SpellCard("操符「少女文乐」", "爱丽丝·玛格特罗依德", SpellCard.H | SpellCard.L),
		new SpellCard("苍符「博爱的法兰西人偶」", "爱丽丝·玛格特罗依德", SpellCard.E | SpellCard.N | SpellCard.H),
		new SpellCard("苍符「博爱的奥尔良人偶」", "爱丽丝·玛格特罗依德", SpellCard.L),
		new SpellCard("红符「红发的荷兰人偶」", "爱丽丝·玛格特罗依德", SpellCard.E | SpellCard.N),
		new SpellCard("白符「白垩的俄罗斯人偶」", "爱丽丝·玛格特罗依德", SpellCard.H | SpellCard.L),
		new SpellCard("暗符「雾之伦敦人偶」", "爱丽丝·玛格特罗依德", SpellCard.E | SpellCard.N),
		new SpellCard("回符「轮回的西藏人偶」", "爱丽丝·玛格特罗依德", SpellCard.H),
		new SpellCard("雅符「春之京人偶」", "爱丽丝·玛格特罗依德", SpellCard.L),
		new SpellCard("诅咒「魔彩光的上海人偶」", "爱丽丝·玛格特罗依德", SpellCard.E | SpellCard.N | SpellCard.H),
		new SpellCard("诅咒「上吊的蓬莱人偶」", "爱丽丝·玛格特罗依德", SpellCard.L),
		new SpellCard("弦奏「Guarneri del Gesù」", "露娜萨·普莉兹姆利巴", SpellCard.E | SpellCard.N),
		new SpellCard("神弦「Stradivarius」", "露娜萨·普莉兹姆利巴", SpellCard.H),
		new SpellCard("伪弦「Pseudo Stradivarius」", "露娜萨·普莉兹姆利巴", SpellCard.L),
		new SpellCard("管灵「日野幻想」", "梅露兰·普莉兹姆利巴", SpellCard.E | SpellCard.N),
		new SpellCard("冥管「灵之克里福德」", "梅露兰·普莉兹姆利巴", SpellCard.H),
		new SpellCard("管灵「灵之克里福德」", "梅露兰·普莉兹姆利巴", SpellCard.L),
		new SpellCard("冥键「法吉奥里冥奏」", "莉莉卡·普莉兹姆利巴", SpellCard.E | SpellCard.N),
		new SpellCard("键灵「蓓森朵芙神奏」", "莉莉卡·普莉兹姆利巴", SpellCard.H | SpellCard.L),
		new SpellCard("骚符「幽灵絮语」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.E | SpellCard.N),
		new SpellCard("骚符「活着的骚灵」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.H | SpellCard.L),
		new SpellCard("合葬「棱镜协奏曲」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.E | SpellCard.N),
		new SpellCard("骚葬「冥河边缘」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.H | SpellCard.L),
		new SpellCard("大合葬「灵车大协奏曲」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.E | SpellCard.N),
		new SpellCard("大合葬「灵车大协奏曲改」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.H),
		new SpellCard("大合葬「灵车大协奏曲怪」", "露娜萨·普莉兹姆利巴&梅露兰·普莉兹姆利巴&莉莉卡·普莉兹姆利巴", SpellCard.L),
		new SpellCard("幽鬼剑「妖童饿鬼之断食」", "魂魄妖梦", SpellCard.E | SpellCard.N),
		new SpellCard("饿鬼剑「饿鬼道草纸」", "魂魄妖梦", SpellCard.H),
		new SpellCard("饿王剑「饿鬼十王的报应」", "魂魄妖梦", SpellCard.L),
		new SpellCard("狱界剑「二百由旬之一闪」", "魂魄妖梦", SpellCard.E | SpellCard.N),
		new SpellCard("狱炎剑「业风闪影阵」", "魂魄妖梦", SpellCard.H),
		new SpellCard("狱神剑「业风神闪斩」", "魂魄妖梦", SpellCard.L),
		new SpellCard("畜趣剑「无为无策之冥罚」", "魂魄妖梦", SpellCard.E | SpellCard.N),
		new SpellCard("修罗剑「现世妄执」", "魂魄妖梦", SpellCard.H | SpellCard.L),
		new SpellCard("人界剑「悟入幻想」", "魂魄妖梦", SpellCard.E | SpellCard.N),
		new SpellCard("人世剑「大悟显晦」", "魂魄妖梦", SpellCard.H),
		new SpellCard("人神剑「俗谛常住」", "魂魄妖梦", SpellCard.L),
		new SpellCard("天上剑「天人之五衰」", "魂魄妖梦", SpellCard.E | SpellCard.N),
		new SpellCard("天界剑「七魄忌讳」", "魂魄妖梦", SpellCard.H),
		new SpellCard("天神剑「三魂七魄」", "魂魄妖梦", SpellCard.H),
		new SpellCard("六道剑「一念无量劫」", "魂魄妖梦", SpellCard.E | SpellCard.N | SpellCard.H | SpellCard.L),
		new SpellCard("亡乡「亡我乡 -彷徨的灵魂-」", "西行寺幽幽子", SpellCard.E),
		new SpellCard("亡乡「亡我乡 -宿罪-」", "西行寺幽幽子", SpellCard.N),
		new SpellCard("亡乡「亡我乡 -无道之路-」", "西行寺幽幽子", SpellCard.H),
		new SpellCard("亡乡「亡我乡 -自尽-」", "西行寺幽幽子", SpellCard.L),
		new SpellCard("亡舞「生者必灭之理 -眩惑-」", "西行寺幽幽子", SpellCard.E),
		new SpellCard("亡舞「生者必灭之理 -死蝶-」", "西行寺幽幽子", SpellCard.N),
		new SpellCard("亡舞「生者必灭之理 -毒蛾-」", "西行寺幽幽子", SpellCard.H),
		new SpellCard("亡舞「生者必灭之理 -魔境-」", "西行寺幽幽子", SpellCard.L),
		new SpellCard("华灵「死蝶」", "西行寺幽幽子", SpellCard.E),
		new SpellCard("华灵「燕尾蝶」", "西行寺幽幽子", SpellCard.N),
		new SpellCard("华灵「深固难徙之蝶」", "西行寺幽幽子", SpellCard.H),
		new SpellCard("华灵「蝶幻」", "西行寺幽幽子", SpellCard.L),
		new SpellCard("幽曲「埋骨于弘川 -伪灵-」", "西行寺幽幽子", SpellCard.E),
		new SpellCard("幽曲「埋骨于弘川 -亡灵-」", "西行寺幽幽子", SpellCard.N),
		new SpellCard("幽曲「埋骨于弘川 -幻灵-」", "西行寺幽幽子", SpellCard.H),
		new SpellCard("幽曲「埋骨于弘川 -神灵-」", "西行寺幽幽子", SpellCard.L),
		new SpellCard("樱符「完全墨染的樱花 -封印-」", "西行寺幽幽子", SpellCard.E),
		new SpellCard("樱符「完全墨染的樱花 -亡我-」", "西行寺幽幽子", SpellCard.N),
		new SpellCard("樱符「完全墨染的樱花 -春眠-」", "西行寺幽幽子", SpellCard.H),
		new SpellCard("樱符「完全墨染的樱花 -开花-」", "西行寺幽幽子", SpellCard.L),
		new SpellCard("「反魂蝶 -一分咲-」", "西行寺幽幽子", SpellCard.E),
		new SpellCard("「反魂蝶 -三分咲-」", "西行寺幽幽子", SpellCard.N),
		new SpellCard("「反魂蝶 -五分咲-」", "西行寺幽幽子", SpellCard.H),
		new SpellCard("「反魂蝶 -八分咲-」", "西行寺幽幽子", SpellCard.L),
		new SpellCard("式神「仙狐思念」", "八云蓝", SpellCard.Ex),
		new SpellCard("式神「十二神将之宴」", "八云蓝", SpellCard.Ex),
		new SpellCard("式辉「狐狸妖怪镭射」", "八云蓝", SpellCard.Ex),
		new SpellCard("式辉「迷人的四面楚歌」", "八云蓝", SpellCard.Ex),
		new SpellCard("式辉「天狐公主 -Illusion-」", "八云蓝", SpellCard.Ex),
		new SpellCard("式弹「往生极乐的佛教徒」", "八云蓝", SpellCard.Ex),
		new SpellCard("式弹「片面义务契约」", "八云蓝", SpellCard.Ex),
		new SpellCard("式神「橙」", "八云蓝", SpellCard.Ex),
		new SpellCard("「狐狗狸的契约」", "八云蓝", SpellCard.Ex),
		new SpellCard("幻神「饭纲权现降临」", "八云蓝", SpellCard.Ex),
		new SpellCard("式神「前鬼后鬼的守护」", "八云蓝", SpellCard.Ph),
		new SpellCard("式神「凭依荼吉尼天」", "八云蓝", SpellCard.Ph),
		new SpellCard("结界「梦境与现实的诅咒」", "八云紫", SpellCard.Ph),
		new SpellCard("结界「动与静的均衡」", "八云紫", SpellCard.Ph),
		new SpellCard("结界「光与暗的网孔」", "八云紫", SpellCard.Ph),
		new SpellCard("罔两「直与曲的梦乡」", "八云紫", SpellCard.Ph),
		new SpellCard("罔两「八云紫的神隐」", "八云紫", SpellCard.Ph),
		new SpellCard("罔两「栖息于禅寺的妖蝶」", "八云紫", SpellCard.Ph),
		new SpellCard("魍魉「二重黑死蝶」", "八云紫", SpellCard.Ph),
		new SpellCard("式神「八云蓝」", "八云紫", SpellCard.Ph),
		new SpellCard("「人与妖的境界」", "八云紫", SpellCard.Ph),
		new SpellCard("结界「生与死的境界」", "八云紫", SpellCard.Ph),
		new SpellCard("紫奥义「弹幕结界」", "八云紫", SpellCard.Ph)
	};
}
