import m.*;

public class Main {
	public static void main(String[] args) {
		SpellCardBuilder scb=new SpellCardBuilder()
		.setMaster("琪露诺")
			.addSpell("冰符「冰袭方阵」", 2, 3)

			.setMaster("蕾蒂·霍瓦特洛克")
			.addSpell("寒符「延长的冬日」", 0, 1, 2, 3)
			.addSpell("冬符「花之凋零」", 0, 1)
			.addSpell("白符「波状光」", 2)
			.addSpell("怪符「桌灵转」", 3)

			.setMaster("橙")
			.addSpell("仙符「凤凰卵」", 0, 1)
			.addSpell("仙符「凤凰展翅」", 2, 3)
			.addSpell("式符「飞翔晴明」", 1, 2)
			.addSpell("阴阳「道满晴明」", 2)
			.addSpell("阴阳「晴明大纹」", 3)
			.addSpell("天符「天仙鸣动」", 0, 1)
			.addSpell("翔符「飞翔韦驮天」", 2)
			.addSpell("童符「护法天童乱舞」", 3)
			.addSpell("仙符「尸解永远」", 0, 1)
			.addSpell("鬼符「鬼门金神」", 2)
			.addSpell("方符「奇门遁甲」", 3)
			.addSpell("鬼符「青鬼赤鬼」", 4)
			.addSpell("鬼神「飞翔毘沙门天」", 4)

			.setMaster("爱丽丝·玛格特罗依德")
			.addSpell("操符「少女文乐」", 2, 3)
			.addSpell("苍符「博爱的法兰西人偶」", 0, 1, 2)
			.addSpell("苍符「博爱的奥尔良人偶」", 3)
			.addSpell("红符「红发的荷兰人偶」", 0, 1)
			.addSpell("白符「白垩的俄罗斯人偶」", 2, 3)
			.addSpell("暗符「雾之伦敦人偶」", 0, 1)
			.addSpell("回符「轮回的西藏人偶」", 2)
			.addSpell("雅符「春之京人偶」", 3)
			.addSpell("诅咒「魔彩光的上海人偶」", 0, 1, 2) 
			.addSpell("诅咒「上吊的蓬莱人偶」", 3)

			.setMaster("露娜萨·普莉兹姆利巴")
			.addSpell("弦奏「Guarneri del Gesù」", 0, 1)
			.addSpell("神弦「Stradivarius」", 2)
			.addSpell("伪弦「Pseudo Stradivarius」", 3)

			.setMaster("梅露兰·普莉兹姆利巴")
			.addSpell("管灵「日野幻想」", 0, 1)
			.addSpell("冥管「灵之克里福德」", 2)
			.addSpell("管灵「灵之克里福德」", 3)

			.setMaster("莉莉卡·普莉兹姆利巴")
			.addSpell("冥键「法吉奥里冥奏」", 0, 1)
			.addSpell("键灵「蓓森朵芙神奏」", 2, 3)

			.setMaster("普莉兹姆利巴姐妹")
			.addSpell("骚符「幽灵絮语」", 0, 1)
			.addSpell("骚符「活着的骚灵」", 2, 3)
			.addSpell("合葬「棱镜协奏曲」", 0, 1)
			.addSpell("骚葬「冥河边缘」", 2, 3)
			.addSpell("大合葬「灵车大协奏曲」", 0, 1)
			.addSpell("大合葬「灵车大协奏曲改」", 2)
			.addSpell("大合葬「灵车大协奏曲怪」", 3)

			.setMaster("魂魄妖梦")
			.addSpell("幽鬼剑「妖童饿鬼之断食」", 0, 1)
			.addSpell("饿鬼剑「饿鬼道草纸」", 2)
			.addSpell("饿王剑「饿鬼十王的报应」", 3)
			.addSpell("狱界剑「二百由旬之一闪」", 0, 1)
			.addSpell("狱炎剑「业风闪影阵」", 2)
			.addSpell("狱神剑「业风神闪斩」", 3)
			.addSpell("畜趣剑「无为无策之冥罚」", 0, 1)
			.addSpell("修罗剑「现世妄执」", 2, 3)
			.addSpell("人界剑「悟入幻想」", 0, 1)
			.addSpell("人世剑「大悟显晦」", 2)
			.addSpell("人神剑「俗谛常住」", 3)
			.addSpell("天上剑「天人之五衰」", 0, 1)
			.addSpell("天界剑「七魄忌讳」", 2)
			.addSpell("天神剑「三魂七魄」", 2)
			.addSpell("六道剑「一念无量劫」", 0, 1, 2, 3)

			.setMaster("西行寺幽幽子")
			.addSpell("亡乡「亡我乡 -彷徨的灵魂-」", 0)
			.addSpell("亡乡「亡我乡 -宿罪-」",  1)
			.addSpell("亡乡「亡我乡 -无道之路-」", 2)
			.addSpell("亡乡「亡我乡 -自尽-」", 3)
			.addSpell("亡舞「生者必灭之理 -眩惑-」", 0)
			.addSpell("亡舞「生者必灭之理 -死蝶-」", 1)
			.addSpell("亡舞「生者必灭之理 -毒蛾-」", 2)
			.addSpell("亡舞「生者必灭之理 -魔境-」", 3)
			.addSpell("华灵「死蝶」", 0)
			.addSpell("华灵「燕尾蝶」", 1)
			.addSpell("华灵「深固难徙之蝶」", 2)
			.addSpell("华灵「蝶幻」", 3)
			.addSpell("幽曲「埋骨于弘川 -伪灵-」", 0)
			.addSpell("幽曲「埋骨于弘川 -亡灵-」", 1)
			.addSpell("幽曲「埋骨于弘川 -幻灵-」", 2)
			.addSpell("幽曲「埋骨于弘川 -神灵-」", 3)
			.addSpell("樱符「完全墨染的樱花 -封印-」", 0)
			.addSpell("樱符「完全墨染的樱花 -亡我-」", 1)
			.addSpell("樱符「完全墨染的樱花 -春眠-」", 2)
			.addSpell("樱符「完全墨染的樱花 -开花-」", 3)
			.addSpell("「反魂蝶 -一分咲-」", 0)
			.addSpell("「反魂蝶 -三分咲-」", 1)
			.addSpell("「反魂蝶 -五分咲-」", 2)
			.addSpell("「反魂蝶 -八分咲-」", 3)

			.setMaster("八云蓝")
			.addSpell("式神「仙狐思念」", 4)
			.addSpell("式神「十二神将之宴」", 4)
			.addSpell("式辉「狐狸妖怪镭射」", 4)
			.addSpell("式辉「迷人的四面楚歌」", 4)
			.addSpell("式辉「天狐公主 -Illusion-」", 4)
			.addSpell("式弹「往生极乐的佛教徒」", 4)
			.addSpell("式弹「片面义务契约」", 4)
			.addSpell("式神「橙」", 4)
			.addSpell("「狐狗狸的契约」", 4)
			.addSpell("幻神「饭纲权现降临」", 4)
			.addSpell("式神「前鬼后鬼的守护」", 5)
			.addSpell("式神「凭依荼吉尼天」", 5)

			.setMaster("八云紫")
			.addSpell("结界「梦境与现实的诅咒」", 5)
			.addSpell("结界「动与静的均衡」", 5)
			.addSpell("结界「光与暗的网孔」", 5)
			.addSpell("罔两「直与曲的梦乡」", 5)
			.addSpell("罔两「八云紫的神隐」", 5)
			.addSpell("罔两「栖息于禅寺的妖蝶」", 5)
			.addSpell("魍魉「二重黑死蝶」", 5)
			.addSpell("式神「八云蓝」", 5)
			.addSpell("「人与妖的境界」",  5)
			.addSpell("结界「生与死的境界」",  5)
			.addSpell("紫奥义「弹幕结界」", 5);

		System.out.println(scb.getSpell());
	}
}
